<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
    <script>
      const test = () => {
        try {
          console.log("a 입니다.");
          throw "강제예외";
        } catch (error) {
          console.log("b 입니다. 에러가 났네요:", error);
          return; // 함수에서 바로 탈출한다.
        }
        console.log("c 입니다."); // 앞서 return 으로 인해 이 코드는 실행되지 않는다.
        // 단 finally 안에 위 코드를 입력해두면 실행된다. finally는 try~catch 문이 있으면 무조건 실행됨.
      };
      test();
    </script>
  </head>
  <body></body>
</html>
